import userModel from "../models/userModel";
import bcrypt from 'bcrypt'
import jwt from "jsonwebtoken";

export const registerUser= async(req,res)=>{
    try {
        const {name,email,password}=req.body;
        if(!name || !email || !password){
            return res.json({success:false,message:'Missing details'})
        }
        const salt=await bcrypt.genSalt(10)
        const hashedPassword= await bcrypt.hash(password,salt)
        const userData={
            name,
            email,
            password:hashedPassword
        }
        const newUser=new userModel(userData)
        const user= await newUser.save() //to save a new user in the database
        const token=jwt.sign({id:user._id},process.env.JWT_SECRET)//_id is automatically generated by the mongodb
        res.json({success:true,token,user:{name:user.name}})//we sending this back to user
    } catch (error) {
        console.log(error)
        res.json({success:false,message:error.message})
    }
}